---

- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  connection: local
  hosts: all
  gather_facts: True

  tasks:
    - name: GET VLANS IN REAL TIME
      ntc_show_command:
        connection: ssh
        platform: avaya_ers
        command: 'show vlan'
        use_keys: false
        host: "{{ ansible_host }}"
        username: "{{ custom_username }}"
        password: "{{ custom_password }}"
      register: result

    - name: SHOW VLANS
      debug: var=result
