---

- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  connection: local
  hosts: all
  gather_facts: False

  tasks:

    - name: GET VLANS IN REAL TIME
      ntc_config_command:
        connection: telnet
        platform: avaya_ers
        commands:
          - show vlan
        use_keys: false
      register: result

    - name: SHOW VLANS
      debug: var=result
