---

language: python

python:
  - "2.7"

sudo: false

install:
  - git clone https://github.com/ktbyers/netmiko.git
  - cd netmiko
  - python setup.py install
  - pip install -r requirements.txt
  - cd ..
  - wget https://pypi.python.org/packages/source/g/gtextfsm/gtextfsm-0.2.1.tar.gz
  - tar -xzvf gtextfsm-0.2.1.tar.gz
  - cd gtextfsm-0.2.1
  - python setup.py install
  - cd ..
  - export PYTHONPATH=$PYTHONPATH:/home/travis/build/networktocode/ntc-templates/gtextfsm-0.2.1/textfsm
  - pip install ansible==1.9.2
  - pip install terminal
  - git clone https://github.com/networktocode/ntc-ansible.git


script:
  - python test-templates.py
